name: Bug Report
description: File a bug report
title: "[Bug]:"
labels: ["bug", "triage"]

body:
  - type: checkboxes
    id: existingcheck
    attributes:
      label: Do you need to file an issue?
      description: Please help us manage our time by avoiding duplicates and common bugs with the steps below.
      options:
        - label: I have searched the existing issues and this bug is not already filed.
        - label: I believe this is a legitimate bug, not just a question or feature request.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
  - type: dropdown
    id: module
    attributes:
      label: Related Module
      description: Which module is this bug related to?
      options:
        - Dashboard
        - Knowledge Base Management
        - Smart Solver
        - Question Generator
        - Deep Research
        - Co-Writer
        - Notebook
        - Guided Learning
        - Idea Generation
        - API/Backend
        - Frontend/Web
        - Other
    validations:
      required: true
  - type: textarea
    id: configused
    attributes:
      label: Configuration Used
      description: The DeepTutor configuration used (if applicable).
      placeholder: |
        # Paste your config here or describe the settings
  - type: textarea
    id: screenshotslogs
    attributes:
      label: Logs and screenshots
      description: If applicable, add screenshots and logs to help explain your problem.
      placeholder: Add logs and screenshots here
  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: |
        - DeepTutor Version: e.g., v0.5.0
        - Operating System: e.g., macOS 14.0, Windows 11, Ubuntu 22.04
        - Python Version: e.g., 3.10.0
        - Node.js Version: e.g., 18.17.0
        - Browser (if applicable): e.g., Chrome 120, Firefox 121
        - Related Issues: e.g., #1
        - Any other relevant information.
      value: |
        - DeepTutor Version:
        - Operating System:
        - Python Version:
        - Node.js Version:
        - Browser (if applicable):
        - Related Issues:
